**ASSIGNMENT 3:Create a Neural networking model on IRIS DATASET using tensorflow**

In [37]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from sklearn import datasets
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical
from sklearn.datasets import load_iris

In [38]:
df=pd.read_csv('/content/Iris.csv')
df.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [39]:
df.shape

(150, 6)

In [41]:
#dont want ID column so i drop
df.drop(labels=['Id'],axis=1,inplace=True)
print(df)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]


In [51]:
df.dtypes

SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [57]:
#split the data into 2 
x=df.iloc[:,:-1].values
y=df.iloc[:,4].values

In [46]:
#categorial to numeric
df["Species"].map({"Iris-setosa":0,"Iris-virginica":1,"Iris-versicolor":2})

0      0
1      0
2      0
3      0
4      0
      ..
145    1
146    1
147    1
148    1
149    1
Name: Species, Length: 150, dtype: int64

SPLIT THE DATASET

In [77]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1=encoder.fit_transform(y)

In [78]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [80]:
y= pd.get_dummies(y1).values
print(y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [83]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=43)

applying layers and model creation

In [84]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3)
  ])
model

compiling model

In [85]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

fit the model

In [86]:
model.fit(x_train, y_train, batch_size=50, epochs=100)

Epoch 1/100
3/3 [==============================] - 1s 6ms/step - loss: 2.8542 - accuracy: 0.3524
Epoch 2/100
3/3 [==============================] - 0s 5ms/step - loss: 1.8333 - accuracy: 0.3524
Epoch 3/100
3/3 [==============================] - 0s 6ms/step - loss: 1.5331 - accuracy: 0.3524
Epoch 4/100
3/3 [==============================] - 0s 5ms/step - loss: 1.4512 - accuracy: 0.3524
Epoch 5/100
3/3 [==============================] - 0s 5ms/step - loss: 1.4038 - accuracy: 0.3524
Epoch 6/100
3/3 [==============================] - 0s 7ms/step - loss: 1.3687 - accuracy: 0.3524
Epoch 7/100
3/3 [==============================] - 0s 6ms/step - loss: 1.3405 - accuracy: 0.3524
Epoch 8/100
3/3 [==============================] - 0s 6ms/step - loss: 1.3157 - accuracy: 0.3524
Epoch 9/100
3/3 [==============================] - 0s 8ms/step - loss: 1.2948 - accuracy: 0.3524
Epoch 10/100
3/3 [==============================] - 0s 5ms/step - loss: 1.2770 - accuracy: 0.3524
Epoch 11/100
3/3 [===========

accuracy

In [88]:
loss,accuracy = model.evaluate(x_test, y_test,)
print('loss:',loss)
print('accuracy:',accuracy)

2/2 [==============================] - 0s 6ms/step - loss: 4.6563 - accuracy: 0.3333
loss: 4.656338691711426
accuracy: 0.3333333432674408


prediction

In [91]:
y_pred = model.predict(x_test)
y_pred

array([[ 1.5497898 , -0.29614258, -0.57398236],
       [ 1.503166  , -0.23518819, -0.5183089 ],
       [ 3.6332605 , -1.6664312 , -2.1493552 ],
       [ 2.9511876 , -1.250936  , -1.5796219 ],
       [ 4.589555  , -2.2346594 , -2.589184  ],
       [ 1.5422333 , -0.2637136 , -0.5437817 ],
       [ 3.709519  , -1.7717712 , -2.2382812 ],
       [ 3.0741572 , -1.3405092 , -1.6964823 ],
       [ 2.7486782 , -1.166338  , -1.4754444 ],
       [ 2.5407636 , -1.0203152 , -1.3843712 ],
       [ 1.3806866 , -0.21329936, -0.4926823 ],
       [ 3.5007489 , -1.6061468 , -1.9024614 ],
       [ 4.6109843 , -2.2097228 , -2.4802625 ],
       [ 1.572034  , -0.3017038 , -0.5991488 ],
       [ 3.362069  , -1.4999812 , -1.9172362 ],
       [ 3.2048814 , -1.404798  , -1.770055  ],
       [ 1.7394079 , -0.32095057, -0.6389049 ],
       [ 1.4084467 , -0.21562758, -0.4848014 ],
       [ 3.981539  , -1.9205143 , -2.4606922 ],
       [ 4.4829206 , -2.2135174 , -2.8175356 ],
       [ 1.4642321 , -0.23672566, -0.506